### ISSUE TITLE
Synchronize tags

### ISSUE THREAD

**Issue by chidalgom1503** [Duddy67/abtag#1]
Hi,

Im testing this great component, but I noticed when click in sync articles the tags from the source are not pulled like category or date for example.

Im doing something wrong? or this feature dont came up with this package?

Many thanks!

**Comment by Duddy67** [comment]
Hi and thanks for testing Abtag.

Sorry but I don't understand your question.
What do you mean exactly by "not pulled like category or date" ? 
Could you provide a specific example ?

Thanks.

**Comment by chidalgom1503** [comment]
hi, 
what I mean is when I sync the articles to abtag, extract all the data from the article, like category and date for example right?, but if the article have tags before the sync proccess this info is not synced to abtag (I think this data should have sync to). 

the other thing I noticed is when I click in some article listed in the blog layout of abtag, it takes me to some copy of the article and not the original article. This make some joomla plugins not run at all.

Is there a way to make the links point to the original article instead? 

thanks

**Comment by Duddy67** [comment]
Ok, I got it.

As it is mentioned in the FAQ:
"ABTag only manages the tags selected through the entries. The tags selected through the articles are not taken into account."
Which is sensible as ABTag is designed to use tags only with articles and not with any other Joomla components.
Besides, the users would get confused with tags leading to different component views (ie: com_abtag or com_tags).

Regarding your second question you're correct, ABTag takes you to the com_abtag entry view. 
The reason it doesn't take you to the original article (ie: com_content) is that the relationship between tags and articles set in ABTag would be broken since we're no longer in the com_abtag component. 
ABTag comes with a plugin (abtagplugins) which manages the plugins originaly used with articles (vote, item navigation etc..).

So what are the Joomla plugins which not run that you're talking about ?
